# Generated by Django 5.2.2 on 2025-06-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='menuItem_id',
            new_name='menuitem_id',
        ),
    ]
