# Generated by Django 5.2.2 on 2025-06-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0002_rename_menuitem_id_rating_menuitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='User',
            new_name='user',
        ),
    ]
